# Generated by Django 2.2 on 2020-12-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('sdob', models.DateField()),
                ('smarks', models.FloatField()),
                ('sphone', models.CharField(max_length=10)),
                ('saddr', models.CharField(max_length=100)),
            ],
        ),
    ]
